
var groups = [
	{name: 'a', words:['suche', 'kannst', 'finden', 'was', 'ist', 'such', 'sind', 'im', 'nach', 'internet', 'netz']},
	{name: 'b', words:['hallo', 'hey', 'hi', 'guten tag', 'servus', 'die', 'ahoi', 'Huhu', 'moin', 'grüß dich', 'hallöchen', 'na', 'grüße']},
	{name: 'c', words:['was', 'wieviel', 'wie', 'ist', 'es', 'zeit', 'uhrzeit', 'clock', 'wird', 'spät']},
	{name: 'd', words:['was', 'wie', 'sagt', 'das', 'wetter', 'wird', 'klima', 'wird', 'in']},
	{name: 'e', words:['wie', "geht", 'es', 'dir', 'gehts', 'sag']},
	{name: 'f', words:['wer', 'bist', 'denn', 'stell', 'dich', 'mal', 'vor']},
	{name: 'g', words:['spasst', 'huhrensohn', 'hitler', 'neger', 'dumme', 'dummer', 'sau', 'bitch', 'dünnbrettbohrer', 'blöd', 'poltergeist', 'hasse', 'dich', 'du', 'bist', 'scheiß', 'scheiße', 'scheisse', "halt's", "maul"]},
	{name: 'h', words:['sleepmode', 'stummer', 'stumm', 'schlafmode','schlafmodus', 'silentmode', 'ruhemodus', 'ein', 'anschalten', 'einschalten', 'du', 'kannst', 'reden']},
	{name: 'i', words:['sleepmode','schlafmode', 'stumm', 'stummer', 'beenden', 'silentmode', 'schlafmodus', 'ruhemodus', 'aus','ausschalten', 'sei', 'ruhig', 'stop', 'hör', 'auf', 'zu', 'reden', 'sei', 'ruhig']},
	{name: 'j', words:['was', 'kannst', 'alles', 'für', 'bist', 'zuständig']},
	{name: 'k', words:['konsolenmodus', 'ein', 'starte', 'console', 'kontrollmodus', 'controlemode', 'programmiermodus']},
	{name: 'l', words:['zufallszahl', 'nenne', 'sage', 'zufall']},
	{name: 'm', words:['nehme', 'auf', 'kannst', 'du', 'dir', 'merken', 'speichern', 'speicher', 'eine', 'notiz', 'nimm']},
	{name: 'n', words:['was', 'war', 'wie', 'meine', 'hatte', 'letzte', 'wollte', 'dir', 'merken', 'notizen', 'notiz']},
	{name: 'o', words:['kopf', 'oder', 'zahl']},
	{name: 'p', words:['du', 'hast', 'verloren', 'es', 'nicht', 'geschafft']},
	{name: 'q', words:['du', 'hast', 'gewonnen', 'es', 'geschafft']},
	{name: 'r', words:['datum', 'heute', 'tag', 'welcher', 'wochentag']},
	{name: 's', words:['wie', 'alt', 'bist', 'du', 'wann', 'geboren', 'geburtstag']},
	{name: 't', words:['von', 'wem', 'programmiert', 'wo', 'geboren', 'entstanden']},
	{name: 'u', words:['wecker', 'stelle', 'wecke', 'mich']},
	{name: 'v', words:['licht']},
	{name: 'w', words:['weiblich', 'männlich', 'stimme', 'ändere', 'voice']},
	{name: 'x', words:['mach','das','Licht', 'an']},
	{name: 'y', words:['weiblich', 'männlich', 'stimme', 'ändere', 'voice']},
	{name: 'z', words:['mach', 'das', 'Licht', 'aus']}	
];